language: node_js

node_js:
- "stable"

cache:
  directories:
    - .cache
    - node_modules
    - public

addons:
  sonarcloud:
    organization: "jyeok" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

before_install:
  - npm install -g gatsby-cli

install:
  - npm install

script:
  - npm run build
  - sonar-scanner

# 배포 설정
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
