language: node_js

node_js:
- "stable"

cache:
  directories:
    - .cache
    - node_modules
    - public

before_install:
  - npm install -g gatsby-cli

install:
  - npm install

script:
  - npm run build

# 배포 설정
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master